"""add lat and long coumns

Revision ID: 3516fbb2b725
Revises: 80d02306ca85
Create Date: 2026-05-09 12:52:37.909708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3516fbb2b725'
down_revision: Union[str, Sequence[str], None] = '80d02306ca85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('airports', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airports', 'longitude')
    op.drop_column('airports', 'latitude')
    # ### end Alembic commands ###
