"""add weather table

Revision ID: 7b58075be66c
Revises: 8b27c2439723
Create Date: 2026-05-09 13:57:17.136455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b58075be66c'
down_revision: Union[str, Sequence[str], None] = '8b27c2439723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('airport_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow_depth', sa.Float(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['airport_code'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_code', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
