"""add name to airlines

Revision ID: 80d02306ca85
Revises: f98b63a30798
Create Date: 2026-05-08 14:48:58.761529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d02306ca85'
down_revision: Union[str, Sequence[str], None] = 'f98b63a30798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'name')
    # ### end Alembic commands ###
