"""add noaa station id column

Revision ID: 8b27c2439723
Revises: 3516fbb2b725
Create Date: 2026-05-09 13:15:27.681100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b27c2439723'
down_revision: Union[str, Sequence[str], None] = '3516fbb2b725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('noaa_station_id', sa.String(length=100), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
