"""add flight index

Revision ID: ef5885c16707
Revises: 7b58075be66c
Create Date: 2026-05-11 10:43:30.930382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5885c16707'
down_revision: Union[str, Sequence[str], None] = '7b58075be66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flights_airline_code'), 'flights', ['airline_code'], unique=False)
    op.create_index(op.f('ix_flights_date'), 'flights', ['date'], unique=False)
    op.create_index(op.f('ix_flights_dest_airport'), 'flights', ['dest_airport'], unique=False)
    op.create_index(op.f('ix_flights_origin_airport'), 'flights', ['origin_airport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_origin_airport'), table_name='flights')
    op.drop_index(op.f('ix_flights_dest_airport'), table_name='flights')
    op.drop_index(op.f('ix_flights_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_airline_code'), table_name='flights')
    # ### end Alembic commands ###
