"""create initial table

Revision ID: f98b63a30798
Revises: 80d5a0c8730f
Create Date: 2026-05-07 12:39:32.095537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98b63a30798'
down_revision: Union[str, Sequence[str], None] = '80d5a0c8730f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('airline_code', sa.String(length=2), nullable=False),
    sa.Column('origin_airport', sa.String(length=3), nullable=False),
    sa.Column('dest_airport', sa.String(length=3), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=True),
    sa.Column('scheduled_dep_time', sa.Integer(), nullable=True),
    sa.Column('actual_dep_time', sa.Integer(), nullable=True),
    sa.Column('dep_delay', sa.Float(), nullable=True),
    sa.Column('dep_delay_15', sa.Boolean(), nullable=True),
    sa.Column('arr_time', sa.Integer(), nullable=True),
    sa.Column('scheduled_arr_time', sa.Integer(), nullable=True),
    sa.Column('arr_delay', sa.Float(), nullable=True),
    sa.Column('arr_delay_15', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancellation_code', sa.String(length=1), nullable=True),
    sa.Column('diverted', sa.Boolean(), nullable=True),
    sa.Column('scheduled_elapsed_time', sa.Integer(), nullable=True),
    sa.Column('actual_elapsed_time', sa.Integer(), nullable=True),
    sa.Column('air_time', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('carrier_delay', sa.Float(), nullable=True),
    sa.Column('weather_delay', sa.Float(), nullable=True),
    sa.Column('nas_delay', sa.Float(), nullable=True),
    sa.Column('security_delay', sa.Float(), nullable=True),
    sa.Column('late_aircraft_delay', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['airline_code'], ['airlines.iata_code'], ),
    sa.ForeignKeyConstraint(['dest_airport'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_airport'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('origin_code', sa.String(length=3), nullable=False),
    sa.Column('dest_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['dest_code'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_code'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('origin_code', 'dest_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('flights')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
